### ISSUE TITLE
ERROR: 

### ISSUE THREAD

**Issue by gregorskii** [sbitio/ansible-mysql#1]
Hi there,

This task is throwing an error when monit is not in use.

I believe this code in main.yml is causing the below issue:

```

# Monit.
- name: Configure mysql service in Monit
  action: monit_check
  args:
    type: service
    name: mysql
  when: monit_service is defined and mysql_monit_skip is not false

```

TASK: [sbitmedia.mysql | Configure mysql service in Monit] ********************
fatal: [stagedb] => template error while templating string: no test named false
fatal: [master] => template error while templating string: no test named false
fatal: [slave] => template error while templating string: no test named false

Thank you
